remote_theme: samarsault/texture

title: 대학원생 AI 스터디 블로그
author: Subeen Lee
email: sbrblee7@gmail.com
show_excerpts: true # set to true to show excerpts on the homepage
# baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Anonymous AI Study Group
  tagline: eXplainable AI, Mechanistic Interpretability
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false
  navigation:
    - title: Home
      url: "https://sbrblee.github.io/SAILAB-freshmen-study.github.io/#"
    - title: About
      url: "https://sbrblee.github.io/SAILAB-freshmen-study.github.io/#"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.md

plugins:
  - jekyll-seo-tag